### ISSUE TITLE
Pausing on scroll off doesn't work after use interaction

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer-viewport-autoplay#5]
I don't know why because the code to pause is there.

@nnarhinen - any ideas?

**Comment by phloxic** [comment]
Ah, I see, `scroll.autoplay` is turned off at the first pause ...

**Comment by nnarhinen** [comment]
I thought that's how it should work. The scroll stuff is disabled after first interaction of the player.

**Comment by phloxic** [comment]
Yes, and that leaves players running when you scroll off. See: https://github.com/flowplayer/flowplayer-viewport-autoplay/issues/1#issuecomment-330510889 by @tipiirai 

It's also horrible, especially when the sound is on.
